generate:

purchase:
  api:
    url: "https://api.ote-godaddy.com"
    key: "3mM44UbhEMfvLg_DzdZshRVMZLPhcAKRk5yCe"
    secret: "V9sdTSK5Lgjg11VQttEe7m"
    # url: "https://api.godaddy.com"
    # key: "e52zcL8JWhni_JedFvff2DQJ9GXHGVC7xPe"
    # secret: "PiUXJh29138ntop6YHCiDc"

  contact:
    # 山东省青岛市开平路13号
    address:
      address1: "13 Kaiping Road, Qingdao, Shandong"
      city: "Qingdao"
      country: "CN"
      postal_code: "266042"
      state: "Shandong"
    email: "aa28cn@gmail.com"
    name_first: "Jin Chuan"
    name_last: "Chen"
    phone: "+86.15310830515"

  name_servers:
    - "ns1.dns.com"
    - "ns2.dns.com"

  renew_auto: false
